name: CI using github actions & docker-compose
on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: make .yml file
        run: |
          cd ./src/main/resources
          touch ./application.yml
          touch ./application-oauth.yml
          echo "${{ secrets.YML }}" > ./application.yml
          echo "${{ secrets.OAUTH2_YML }}" > ./application-oauth.yml
        shell: bash

      - name: make docker file
        run: |
          touch ./docker-compose.yml
          echo "${{ secrets.DOCKER_COMPOSE }}" > ./docker-compose.yml
        shell: bash

      - name: Permission for gradlew
        run: chmod +x gradlew

      - name: Build gradle
        run: ./gradlew clean build

      - name: Dockerfile build and push to docker hub
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.USERNAME }}/springbootbook-application .
          docker push ${{ secrets.USERNAME }}/springbootbook-application
