name: CI using github actions & docker-compose
on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 18
        uses: actions/checkout@v3
        with:
          java-version: '18'

      - name: make .yml file
        run: |
          cd ./src/main/resources
          touch ./application.yml
          touch ./application-oauth.yml
          echo "${{ secrets.YML }}" > ./application.yml
          echo "${{ secrets.OAUTH2_YML }}" > ./application-oauth.yml
        shell: bash

      - name: make mail file
        run: |
          cd ./src/main/java/me/banson/springbootbook/config/javamail
          touch ./JavaMailConfig.java
          echo "${{ secrets.JAVAMAIL }}" > ./JavaMailConfig.java
        shell: bash

      - name: make mail file
        run: |
          touch ./docker-compose.yml
          echo "${{ secrets.DOCKER_COMPOSE }}" > ./docker-compose.yml
        shell: bash

      - name: Permission for gradlew
        run: chmod +x gradlew
      - name: Build gradle
        run: ./gradlew clean build

      - name: Docker-compose build
        run: |
          docker-compose up --build
